{{- if .Values.app.isAccessible }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $.Values.app.name }}-http
spec:
  gateways:
  - ketch-{{ $.Values.app.name }}-gateway
  hosts:
{{- range $_, $cname := .Values.app.cnames }}
    - {{ $cname }}
{{- end }}
  http:
  - match:
    - uri:
        prefix: /
    route:
{{- range $_, $deployment := $.Values.app.deployments }}
{{- range $_, $process := $deployment.processes }}
{{- if $process.routable }}
    - destination:
        host: {{ printf "%s-%s-%v" $.Values.app.name $process.name $deployment.version }}
        port:
          number: {{ $process.publicServicePort }}
      weight: {{ $deployment.routingSettings.weight }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
