# permissions for end users to edit frameworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: framework-editor-role
rules:
- apiGroups:
  - theketch.io
  resources:
  - frameworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - theketch.io
  resources:
  - frameworks/status
  verbs:
  - get
