# permissions for end users to view frameworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: framework-viewer-role
rules:
- apiGroups:
  - theketch.io
  resources:
  - frameworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - theketch.io
  resources:
  - frameworks/status
  verbs:
  - get
