{{ range $_, $https := .Values.app.ingress.https }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ $https.secretName }}
  namespace:  default
spec:
  secretName: {{ $https.secretName }}
  dnsNames:
    - {{ $https.cname }}
  issuerRef:
    name: {{ $.Values.ingressController.clusterIssuer }}
    kind: ClusterIssuer
---
{{ end }}